name: CI
on: [push]
jobs:
  container-job:
    name: Implement Chaos
    runs-on: ubuntu-latest
    steps:
    - name: OpenStack Chaos Action
      uses: Viaceslav-Kodesh/Godzilla@master
      with:
        authUrl: ${{ secrets.OS_AUTH_URL }}
        projectName: ${{ secrets.OS_USERNAME }}
        projectDomainName: ${{ secrets.PROJECT_DOMAIN_NAME }}
        userName: ${{ secrets.OS_USERNAME }}
        DomainName: ${{ secrets.OS_USER_DOMAIN_NAME }}
        userPassword: ${{ secrets.OS_PASSWORD }}
